Towelstation13/towelstation13

- code/modules/mob/living/living_say.dm
Reverts https://github.com/Skyrat-SS13/Skyrat-tg/pull/14440
Makes the game better, you can now use the radio while stunned or cuffed. Possibly bring back once we get more pop.
<details>
</details>
:cl:
del: Removed the requirement of your hands to be free to speak over radio.
/:cl:
> Reverts "You can no longer use the radio while cuffed"

- code/__DEFINES/~skyrat_defines/traits.dm
- code/modules/mob/living/carbon/carbon_defense.dm
- modular_skyrat/master_files/code/datums/traits/neutral.dm
Removes an ERP quirk that somehow got left in the game despite that kind of stuff being turned off in the config.
The quirk as it stands, does nothing and ERP actions like ass slapping are against the rules anyways.
<details>
</details>
:cl:
del: Removed the personal space quirk
/:cl:
> Removes the Personal Space quirk

- code/game/objects/items/cigs_lighters.dm
Ports https://github.com/tgstation/tgstation/pull/78202
<details>
</details>
:cl: Jacquerel
fix: It is now possible to smoke cigarettes even if you aren't wearing a safety helmet
/:cl:
> Ports Allows you to smoke cigarettes while not wearing a space helmet

- code/__DEFINES/clothing.dm
- code/datums/components/bakeable.dm
- code/datums/components/crafting/crafting.dm
- code/datums/components/food/edible.dm
- code/datums/components/food/golem_food.dm
- code/datums/components/grillable.dm
- code/datums/elements/dryable.dm
- code/datums/elements/food/microwavable.dm
- code/game/objects/items/food/_food.dm
- code/game/objects/items/robot/items/food.dm
- code/game/objects/structures/morgue.dm
- code/modules/clothing/clothing.dm
- code/modules/food_and_drinks/machinery/processor.dm
- code/modules/reagents/chemistry/machinery/reagentgrinder.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/weird_food.dm
- tgstation.dme
Ports https://github.com/tgstation/tgstation/pull/78190
<details>
</details>
:cl: Jacquerel
fix: Golems can eat
fix: Cooked and crafted food should be edible
fix: Medborgs can now spawn vanilla ice cream instead of nothing ice cream
fix: Ghosts can examine food
/:cl:
> Ports Collected food fixes

- tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx
Fixes https://github.com/Towelstation13/towelstation13/issues/12
Bugs bad.
:cl:
fix: You can once again change species
/:cl:
> Fixes species selection

- modular_skyrat/modules/barricades/code/barricade.dm
- modular_skyrat/modules/cargo/code/packs.dm
Changes the deployable barricades to be C.O.P.E (Complex Obstructive Portable Expanding Barricade). I'm also open to doing away with the acronym entirely and just calling them "deployable barricades" or similar.
Putting a little distance between us and weird stuff. Cope seethe mald.
<details>
</details>
:cl:
spellcheck: Deployable barricades now go by C.O.P.E.
/:cl:
> Renames deployable barricades

- .github/workflows/auto_changelog.yml
- .github/workflows/compile_changelogs.yml
Switching our token secret since we don't use skyratbot
> Set up auto changelog action, hopefully

- code/modules/mob/living/carbon/human/species_types/podpeople.dm
I forced the Google Bard AI to write lore for me.
Having a proper lore in place helps give people a better idea of how to play podpeople characters.
<details>
(Edit: Screenshot is outdated, I fixed the lack of spaces in places)
</details>
:cl:
spellcheck: Gave lore to podpeople
/:cl:
> Gives a proper description and lore to podpeople

- modular_skyrat/master_files/code/modules/client/preferences/headshot.dm
Comments out the line of code locking the headshot feature to admin/donator only.
More people can use a feature that everyone should be able to use.
<details>
It is really hard to test this on a local server, but I think it works :)
</details>
:cl:
qol: Everyone can use the headshot feature now.
/:cl:
> Made it so non-donators can use the headshot feature

- code/_onclick/hud/hud.dm
Fixes https://github.com/Towelstation13/towelstation13/issues/33
Runtime bad :(
:cl:
fix: fixes a runtime I accidentally caused
/:cl:
> Fixes runtime in code/_onclick/hud/action_button.dm, line 283

- modular_skyrat/modules/title_screen/code/new_player.dm
- modular_skyrat/modules/title_screen/code/title_screen_html.dm
- modular_skyrat/modules/title_screen/readme.md
Just as the PR title says, removes a pointless button that has no function.
A less cluttered title screen is better.
<details>
</details>
:cl:
del: Removes the server swap button
/:cl:
> Removes the server swap button from the title screen

- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/towelstaton/body_size.tsx
Fixes https://github.com/Towelstation13/towelstation13/issues/27
It fixes a thing I accidentally broke ages ago.
<details>
</details>
:cl:
fix: fixes the body size slider
/:cl:
> Finally fixes body size

- modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/skrell.dm
- modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/tajaran.dm
- modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/unathi.dm
- modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/vox.dm
- modular_skyrat/modules/customization/modules/mob/living/carbon/human/species/vulpkanin.dm
As the title says. I literally took the lore straight from paradise since the species are exactly the same.
More complete species lore.
:cl:
spellcheck: Wrote up lore for more species that lacked it.
/:cl:
> Adds lore to the races imported from Paradise

- modular_skyrat/modules/customization/modules/jobs/_job.dm
Foreigner should be able to play more than just fucking service
Good
<details>
No
</details>
:cl:
balance: non-common speakers can now actually play jobs.
/:cl:
> Non-common :)

- strings/station_names.txt
- strings/station_prefixes.txt
Removes 3 possible words from station name (i dont like them cmon man its 2023)
<details>
</details>
:cl:
del: Removed words we dont want in the station title
/:cl:
> Cmon man its 2023 we dont need these

- _maps/map_files/generic/CentCom_skyrat_z2.dmm
Removes the ERP rooms and replaces them with neat things, or otherwise just replaces double beds with single beds. 
***THE FROG POND IS FROM THE PAHRUMP SURFACE MAP OF THE WASTELAND SS13 SERVER***
No ERP.
<details>
I didn't test it teehee
</details>
:cl:
fix: fixed the ghost cafe having ERP stuff.
/:cl:
> Removes ERP rooms from the ghost cafe

- modular_skyrat/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
Zy told me i could remove restrictions from her donator items. Will eventually have to look through all of them though, and most likely, get rid of half the donator items.
Cool item:tm:
<details>
</details>
:cl:
add: some items aren't tied to a ckey whitelist anymore with permission from the item's creator.
/:cl:
> Makes a few items no longer locked to CKEY

- modular_skyrat/modules/tableflip/code/flipped_table.dm
https://github.com/Skyrat-SS13/Skyrat-tg/pull/24267/files <- Mirror
Its easy to miss someone doing this, but it's a mechanics-heavy action, given how much of a defensive boon a flipped table is. It's useful to notice when someone is doing this.
<details>
</details>
:cl: NikoTheGuyDude
qol: Table flipping feedback is now in the form of balloon alerts
/:cl:
> (MIRROR) Balloon alert table flipping and table flips throw items + fixes

- code/modules/mob_spawn/ghost_roles/mining_roles.dm
- modular_skyrat/modules/ashwalkers/code/buildings/ash_tendril.dm
https://github.com/Skyrat-SS13/Skyrat-tg/pull/24028 <- Mirror
Bugs bad
<details>
</details>
:cl: jjpark-kb
fix: the ashwalker tendril will allow you to respawn again (the tendril blessing)
fix: the round end report will accurately report ashwalker sacrifices
/:cl:
> (MIRROR) fixes the tendril blessing (respawning)

- _maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_ash_walker1_skyrat.dmm
As the title says, gives the ashwalkers a salt geyser in their kitchen so they can get salt
Salt is used in a lot of lizard foods
I didn't test it..
:cl:
qol: gives salt to the ashwalker camp in the form of a geyser
/:cl:
> Literal salt PR | Gives salt to Ashwalkers

- modular_skyrat/modules/ices_events/code/ICES_event_config.dm
Removes the ability for wall fungus to roll, also enables shuttle insurance very rarely. Tweaks the supply pods so syndie supply pods are rarer than normal supply pods (what the hell SR)
Balance.
<details>
N/A
</details>
:cl:
balance: rebalanced random events
config: enabled shuttle insurance
config: disabled wall fungus
/:cl:
> The Fungus is no longer Among Us

- modular_skyrat/modules/pollution/code/pollution.dm
Mirror of https://github.com/Skyrat-SS13/Skyrat-tg/pull/24394
Runtimes bad..
I didn't test it.
> (MIRROR) Fixes runtime spam with pollution

- code/__DEFINES/~skyrat_defines/loadouts.dm
- modular_skyrat/modules/loadouts/loadout_items/_loadout_datum.dm
- modular_skyrat/modules/loadouts/loadout_items/loadout_datum_toys.dm
- modular_skyrat/modules/loadouts/loadout_ui/loadout_manager.dm
Mirror of https://github.com/Skyrat-SS13/Skyrat-tg/pull/24288
More flavour is good.
:cl: Iamgoofball
qol: You can now rename and describe any loadout item, not just plushies.
/:cl:
> (MIRROR) All loadout items can now be renamed and given new descriptions

- _maps/map_files/VoidRaptor/VoidRaptor.dmm
Fixes some issues on void station
map 👍  = gameplay 👍 
<details>
</details>
:cl:
fix: Void raptor detective only has one closet now
fix: Void raptor surgery trays now have tools
/:cl:
> Void raptor fixes/changes

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
As the title says.
People once again have two hands.
:cl:
fix: fixed swapping between hands
/:cl:
> Fixes swapping hands

- code/controllers/configuration/entries/general.dm
- code/datums/world_topic.dm
- code/game/objects/structures/showcase.dm
- code/modules/admin/verbs/server.dm
- code/modules/cargo/packs/security.dm
- code/modules/hydroponics/beekeeping/bee_smoker.dm
- code/modules/mob/dead/new_player/new_player.dm
- code/modules/mob/living/carbon/human/species_types/ethereal.dm
- code/modules/mob/living/carbon/human/species_types/felinid.dm
- code/modules/mob/mob.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
- code/modules/projectiles/guns/energy/stun.dm
- code/modules/uplink/uplink_items/job.dm
- config/config.txt
- modular_skyrat/modules/opposing_force/code/equipment/guns.dm
- tgstation.dme
Reverts Towelstation13/towelstation13#93
> Revert "Fixes respawning"

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Reverts Towelstation13/towelstation13#94
> Revert "Fixes swapping hands"

- tgui/packages/tgui/interfaces/InteractionMenu.tsx
Bugs bad
:cl:
fix: The interact menu no longer bluescreens
/:cl:
> Un-NtOS's the interact menu

- _maps/map_files/Birdshot/birdshot.dmm
- _maps/map_files/KiloStation/KiloStation.dmm
Fixes https://github.com/Towelstation13/towelstation13/issues/105
:cl:
fix: The HoP and Captain once again have ID consoles on Kilo
fix: Gave the Kilo bitrunning den lights
/:cl:
> Minor Kilo Fixes

- _maps/skyrat/automapper/templates/mining/lavaland_ashwalker_nenest.dmm
:cl:
del: removed the ashwalker salt geyser due to saltcane existing now
fix: fixed infinite gutlunches
/:cl:
> Ashwalker base tweaks

- _maps/map_files/KiloStation/KiloStation.dmm
- _maps/skyrat/automapper/automapper_config.toml
Fixed some things on Kilo that was bugging me.
:cl:
fix: Fixed some things on the Kilo map, including the bitrunning den being depowered and the cryo tubes being turned the wrong way.
/:cl:
> Kilo fixes!

- tgui/packages/tgui/interfaces/OpposingForcePanel.jsx
As the title says, hopefully fixes an issue.
:cl:
fix: fixed the OPFOR panel temporarily
/:cl:
> Hopefully fixes the OpFor panel bluescreening

- tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
Just a temporary mirror while I struggle with the main upstream sync..
> Fixes character creation
